name: Release Resumes
on:
  push:
    tags:
      - '*'

jobs:
  build-resumes:
    uses: rohannng/resume/.github/workflows/resume_build.yml@{{github.ref}}

  release-resumes:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body:
            Updated resumes released!
          files: |
            /data/*.pdf
