name: Generate Resumes
on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  generate-resumes:
    runs-on: ubuntu-latest
    container:
      image: rohannng/texlive-full:main
      volumes:
        - ${{ github.workspace }}:/data
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Generate resumes...
        run: |
          make

      - name: List resume pdf files.
        run: |
          ls -ltr /data

      - name: Upload resumes
        uses: actions/upload-artifact@v2
        with:
          name: resumes
          path: /data/*.pdf
