name: Release Resumes
on:
  push:
    tags:
      - '*'

jobs:
  release:
    steps:
      - name: Create Release
        run : echo "Creating release"
      - name: Attaching artifacts
        run : echo "Attaching artifacts"