name: Release Resumes
on:
  push:
    tags:
      - '*'

jobs:
  build-resumes:
    uses: rohannng/resume/.github/workflows/resume_build.yml@main

  release-resumes:
    needs: build-resumes
    runs-on: ubuntu-latest
    steps:
      - name: Download resumes
        uses: actions/download-artifact@v2
        with:
          name: resumes
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body:
            Updated resumes released!
          files: |
            *.pdf
